version: '3'

services:
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb_c
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - my_network
    restart: on-failure
    env_file:
      - .env
  nginx:
    image: nginx
    container_name: nginx_c
    depends_on:
     - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - my_network
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
  wordpress:
    image: wordpress
    container_name: wordpress_c
    depends_on:
     - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - my_network
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env

volumes:
  mariadb:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/${USER}/data/db
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp
 
networks:
  my_network:
    name: my_network
